rules:
  header-max-length: [2, always, 100]

  type-empty: [2, never]
  type-enum: [2, always, [
    feat,
    fix,
    refactor,
    docs,
    test,
    chore,
    revert,
    release,
    nvm
  ]]

  scope-empty: [0, never]
  scope-case: [2, always, lower-case]

  subject-empty: [2, never]
  subject-case: [2, always, sentence-case]
  subject-full-stop: [2, never, '.']

  body-leading-blank: [2, always]
  body-max-line-length: [2, always, 100]
  body-case: [2, always, sentence-case]

  footer-leading-blank: [2, always]
  footer-max-line-length: [2, always, 100]
